# Generated by Django 2.1.2 on 2018-10-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20181026_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='result',
        ),
        migrations.AddField(
            model_name='challenge',
            name='p1result',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='p2result',
            field=models.BooleanField(null=True),
        ),
    ]
